# Generated by Django 4.0.5 on 2022-07-08 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GprsCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ('city',),
            },
        ),
        migrations.CreateModel(
            name='Gprs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=100)),
                ('login_bft', models.CharField(max_length=100)),
                ('password_bft', models.CharField(max_length=100)),
                ('ppp', models.CharField(max_length=100)),
                ('login_ftp', models.CharField(max_length=100)),
                ('password_ftp', models.CharField(max_length=100)),
                ('type_modem', models.CharField(max_length=100)),
                ('imei_modem', models.CharField(max_length=100)),
                ('sim', models.CharField(max_length=100)),
                ('number_sim', models.CharField(max_length=100)),
                ('email_client', models.EmailField(max_length=254)),
                ('date_con', models.DateField()),
                ('description', models.CharField(max_length=300)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gprs_monitor.gprscity')),
            ],
        ),
    ]
