# Generated by Django 4.0.5 on 2022-07-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gprs_monitor', '0003_gprs_operator_sim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gprs',
            name='operator_sim',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('MTS', 'Mts'), ('life', 'Life')], max_length=10),
        ),
    ]
