# Generated by Django 4.0.5 on 2022-08-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gprs_monitor', '0005_alter_gprs_date_con'),
    ]

    operations = [
        migrations.AddField(
            model_name='gprs',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
