# Generated by Django 4.0.5 on 2022-07-04 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ups_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporthistory',
            options={'ordering': ('ups',), 'verbose_name': 'Report history UPS', 'verbose_name_plural': 'Report history UPS'},
        ),
        migrations.RemoveField(
            model_name='ups',
            name='slug',
        ),
    ]
