# Generated by Django 4.0.5 on 2022-07-04 20:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ups_monitor', '0002_alter_reporthistory_options_remove_ups_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporthistory',
            name='last_date_battary_replacement',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reporthistory',
            name='made_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reporthistory',
            name='model',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='reporthistory',
            name='report_selftest',
            field=models.CharField(default='NA', max_length=2),
        ),
        migrations.AlterField(
            model_name='reporthistory',
            name='serial_number',
            field=models.CharField(default='sn0000000', max_length=30),
        ),
        migrations.AlterField(
            model_name='reporthistory',
            name='voltage_battary',
            field=models.FloatField(default=0.0),
        ),
    ]
