# Generated by Django 4.0.5 on 2022-08-01 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ups_monitor', '0003_alter_reporthistory_last_date_battary_replacement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorUPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_con', models.BooleanField(default=False)),
                ('err_main_voltage', models.BooleanField(default=False)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('ups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ups_monitor.ups')),
            ],
            options={
                'verbose_name': 'Error UPS',
                'verbose_name_plural': 'Errors UPS',
                'ordering': ('date_add',),
            },
        ),
    ]
