# Generated by Django 4.0.5 on 2022-08-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ups_monitor', '0004_errorups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errorups',
            name='err_main_voltage',
        ),
        migrations.AddField(
            model_name='statehistory',
            name='low_main_voltage',
            field=models.BooleanField(default=False),
        ),
    ]
